### ISSUE TITLE
start `civkitd` with error message "No such file or directory"

### ISSUE THREAD

**Issue by oneforalone** [civkit/civkit-node#43]
Can not start `civkitd`, i just build civkitd from source and run it on my local machine. However, it failed, just get an error message:
```
Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```
Here is what i did:
1. clone the codes via git: `git clone https://github.com/civkit/civkit-node.git`
2. compile: `pushd civkit-node && cargo build --release`
3. start: `./target/release/civkitd`
and then got the error. 

Seems that I need to create some files or directories. Already tried to copy `example-config.toml` to `config.toml`, not working. Am i missing something?

Here is the OS and rust version I use:
OS: Ubuntu 20.04.3 LTS
Rustc: rustc 1.71.1 (eb26296b5 2023-08-03)

**Comment by ariard** [comment]
Hi oneforalone, thank for the bug report. Yes I’m aware of the issue with data dir and finding `example-config.toml` across platforms. Currently being worked out with #39.

In the meantime, landed #42, let me know if commit 0784068 works. `example-config.toml` should be within `civkit-node/` dir.

**Comment by dapsavoie** [comment]
Could it be because your running `./target/release/civkitd` instead of `./target/debug/civkitd`? This could help. I will work on a resolution for this issue but let me know if the above works temporarily. 

Secondly, ive added a script called check_config.sh on the issue https://github.com/civkit/civkit-node/pull/39 so if that is merged, it could be used to generate example-config.toml manually.

**Comment by oneforalone** [comment]
> In the meantime, landed https://github.com/civkit/civkit-node/pull/42, let me know if commit https://github.com/civkit/civkit-node/commit/0784068d557c012e6fa542aa66fd6779473eaa44 works. example-config.toml should be within civkit-node/ dir.
Emm. This does not work properly, cause i believe it does not read the config file at all. I now start it with error that `Failed to bind to listen port: Os { code: 98, kind: AddrInUse, message: "Address already in use" }', src/server.rs:375:97`, seems that you hardcode listenning ports? I tried to change the ports in `example-config.toml`, and start it again, error remains the same.

**Comment by oneforalone** [comment]
@dapsavoie > you could create the file manually and it should work in the meantime.

I believe the proper way to do is check if the config file exists, otherwise the civkitd should create a default config file. I'll check the source code to see how i can make this happen when i'm free.

**Comment by dapsavoie** [comment]
@oneforalone we are working on something similar here to check if config exists then create it https://github.com/civkit/civkit-node/pull/39. 

for the 2nd issue you encountered, i usually run pkill -9 civkitd to kill all running civkit instances then relaunch it. thats how ive been getting around the error of address already in use.

**Comment by ariard** [comment]
> This does not work properly, cause i believe it does not read the config file at all. I now start it with error that Failed to bind to listen port: Os { code: 98, kind: AddrInUse, message: "Address already in use" }', 

Yes this can be an expected behavior if you’ve already running Lightning software on port 9735, the port documented in BOLT1 https://github.com/lightning/bolts/blob/master/01-messaging.md So here a solution can be to kill running Lightning software, if it can be done in a non-disruptive way.

This is not a choice mistake as one of the design goal of the Civkit node is to be fully-compatible peer within the Lightning network infrastructure to leverage onion routing and all the gossips mechanisms, among other.

The other default ports, which to the best of my knowledge do not conflict with well known UNIX services:
- nostr relay port: 50021
- CLI connections: 50031

Currently, you cannot pass the port values in the config file, though it can be done as command line options in the following ways:

```
./civkitd --noise-port 60001 --nostr-port 60011 --cli-port 60021
```

Let me know if it fixes thing ?

**Comment by oneforalone** [comment]
> Currently, you cannot pass the port values in the config file, though it can be done as command line options in the following ways: `./civkitd --noise-port 60001 --nostr-port 60011 --cli-port 60021`

It works, thanks for your effort.
